services:
  api:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/media_pipeline
      REDIS_HOST: redis
      S3_ENDPOINT: http://localstack:4566
    depends_on:
      - mongo
      - redis
      - localstack

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  localstack:
    image: localstack/localstack:3.8
    environment:
      SERVICES: s3
      S3_SKIP_SIGNATURE_VALIDATION: 0
    ports:
      - '4566:4566'
    volumes:
      - ./docker/localstack/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh

volumes:
  mongodata:
